/**
 * Diagnose installment progress for Kirsten Celesse J. Mahinay
 * (cherryjaodmd@gmail.com) — profile 123, class 47.
 *
 * Compares:
 *   - Raw DB fields (generated_count, invoices, enrollments)
 *   - Installment Invoice Logs list progress (paid_phases / generated_phases SQL)
 *   - Student History phases API progress (plan_slots_addressed, paid/generated counts)
 *   - Expected values when enrollment starts on class phase 2 (not phase 1)
 *
 * Run:
 *   node backend/scripts/diagnoseKirstenMahinayInstallmentProgress.js
 */

import '../config/loadEnv.js';
import { query } from '../config/database.js';
import pool from '../config/database.js';
import { parseTargetPhase } from '../utils/balanceInvoice.js';
import {
  annotateInstallmentPhasePlanSlots,
  attachEnrollmentToInstallmentPhaseRows,
  isAdvancePaymentInvoice,
  isAutoGeneratedInstallmentInvoice,
  isCancelledInvoiceChain,
  loadEnrollmentStatusByAbsolutePhase,
  mapPhaseChainsToLocalSlots,
  normalizeAdjacentPhaseDisplayDates,
} from '../utils/installmentPhaseRowMapping.js';
import {
  loadActiveEnrollmentAbsolutePhases,
  loadDroppedAbsolutePhasesForProfile,
} from '../utils/installmentPhaseBillingSync.js';
import {
  computeInstallmentPhaseDisplayStatus,
  resolveInstallmentGraceDays,
} from '../utils/programPaymentStatusService.js';
import {
  getCurrentInstallmentPhaseNumber,
  resolveProfilePhaseStart,
} from '../utils/phaseInstallmentUtils.js';
import { todayYmdManila } from '../utils/dateUtils.js';

const STUDENT_EMAIL = 'cherryjaodmd@gmail.com';
const PROFILE_ID = 123;
const STUDENT_ID = 109;
const CLASS_ID = 47;

const section = (title) => console.log(`\n${'='.repeat(72)}\n${title}\n${'='.repeat(72)}`);

const studentRes = await query(
  `SELECT user_id, full_name, email FROM userstbl WHERE email = $1 LIMIT 1`,
  [STUDENT_EMAIL]
);
if (!studentRes.rows[0]) {
  console.error(`Student not found: ${STUDENT_EMAIL}`);
  process.exit(1);
}

section(`Student: ${studentRes.rows[0].full_name} (${STUDENT_EMAIL})`);

const profileRes = await query(
  `SELECT ip.*, c.class_name, p.program_name
   FROM installmentinvoiceprofilestbl ip
   LEFT JOIN classestbl c ON c.class_id = ip.class_id
   LEFT JOIN programstbl p ON p.program_id = c.program_id
   WHERE ip.installmentinvoiceprofiles_id = $1`,
  [PROFILE_ID]
);
const profile = profileRes.rows[0];
if (!profile) {
  console.error(`Profile ${PROFILE_ID} not found`);
  process.exit(1);
}

const phaseStart = resolveProfilePhaseStart(profile);
const phaseStartOffset = Math.max(0, phaseStart - 1);

section('A — Profile & enrollment (DB)');
console.table([
  {
    profile_id: profile.installmentinvoiceprofiles_id,
    class_id: profile.class_id,
    class_name: profile.class_name,
    total_phases: profile.total_phases,
    phase_start: profile.phase_start,
    generated_count: profile.generated_count,
    downpayment_paid: profile.downpayment_paid,
    downpayment_invoice_id: profile.downpayment_invoice_id,
    is_active: profile.is_active,
    per_phase_amount: profile.amount,
  },
]);

const enrollRes = await query(
  `SELECT classstudent_id, phase_number, program_enrollment_status,
          TO_CHAR(enrolled_at, 'YYYY-MM-DD') AS enrolled_at,
          TO_CHAR(removed_at, 'YYYY-MM-DD') AS removed_at
   FROM classstudentstbl
   WHERE student_id = $1 AND class_id = $2
   ORDER BY phase_number, classstudent_id`,
  [STUDENT_ID, CLASS_ID]
);
console.log('\nEnrollment rows:');
console.table(enrollRes.rows);

const activeEnrollmentPhases = await loadActiveEnrollmentAbsolutePhases(pool, STUDENT_ID, CLASS_ID);
const firstEnrolledPhase = Math.min(...[...activeEnrollmentPhases]);
console.log(`Active enrollment class phases: [${[...activeEnrollmentPhases].sort((a, b) => a - b).join(', ')}]`);
console.log(`First enrolled class phase: ${Number.isFinite(firstEnrolledPhase) ? firstEnrolledPhase : '—'}`);

const invoices = (
  await query(
    `SELECT i.invoice_id, i.status, i.amount, i.invoice_ar_number, i.remarks,
            TO_CHAR(i.issue_date, 'YYYY-MM-DD') AS issue_date,
            TO_CHAR(i.due_date, 'YYYY-MM-DD') AS due_date,
            i.installmentinvoiceprofiles_id,
            COALESCE(i.invoice_chain_root_id, i.invoice_id) AS chain_root_id,
            COALESCE((
              SELECT SUM(COALESCE(p.payable_amount, 0) + COALESCE(p.discount_amount, 0))
              FROM paymenttbl p
              WHERE p.invoice_id = i.invoice_id
                AND p.status = 'Completed'
                AND COALESCE(p.approval_status, 'Pending') <> 'Rejected'
            ), 0)::numeric AS paid_total
     FROM invoicestbl i
     WHERE i.installmentinvoiceprofiles_id = $1
        OR i.invoice_id IN (310, 311, 571, 1012, 1511)
     ORDER BY i.invoice_id`,
    [PROFILE_ID]
  )
).rows.map((row) => ({
  ...row,
  target_phase: parseTargetPhase(row.remarks),
}));

console.log('\nLinked invoices:');
console.table(
  invoices.map((r) => ({
    invoice_id: r.invoice_id,
    on_profile: r.installmentinvoiceprofiles_id,
    status: r.status,
    target_phase: r.target_phase,
    issue_date: r.issue_date,
    due_date: r.due_date,
    ar: r.invoice_ar_number,
    paid: r.paid_total,
  }))
);

section('B — Installment Invoice Logs progress (list SQL)');
const listProgressRes = await query(
  `SELECT
     (SELECT COUNT(DISTINCT COALESCE(i.invoice_chain_root_id, i.invoice_id))::integer
      FROM invoicestbl i
      WHERE i.installmentinvoiceprofiles_id = $1
        AND i.status = 'Paid'
        AND (
          $2::int IS NULL OR
          COALESCE(i.invoice_chain_root_id, i.invoice_id) != $2::int
        )
     ) AS paid_phases,
     (SELECT COUNT(DISTINCT COALESCE(i.invoice_chain_root_id, i.invoice_id))::integer
      FROM invoicestbl i
      WHERE i.installmentinvoiceprofiles_id = $1
        AND (
          $2::int IS NULL OR
          COALESCE(i.invoice_chain_root_id, i.invoice_id) != $2::int
        )
     ) AS generated_phases,
     COALESCE(ip.generated_count, 0)::integer AS profile_generated_count,
     (SELECT MAX(cs.phase_number)::integer
      FROM classstudentstbl cs
      WHERE cs.student_id = ip.student_id
        AND cs.class_id = ip.class_id
        AND cs.removed_at IS NULL
        AND cs.phase_number IS NOT NULL
     ) AS last_enrolled_phase_number
   FROM installmentinvoiceprofilestbl ip
   WHERE ip.installmentinvoiceprofiles_id = $1`,
  [PROFILE_ID, profile.downpayment_invoice_id]
);
const listProgress = listProgressRes.rows[0];
const paidPhases = Number(listProgress.paid_phases || 0);
const generatedPhases = Number(listProgress.generated_phases || 0);
const profileGeneratedCount = Number(listProgress.profile_generated_count || 0);
const lastEnrolledPhase = listProgress.last_enrolled_phase_number != null
  ? Number(listProgress.last_enrolled_phase_number)
  : null;
const billedPhaseProgress = Math.max(paidPhases, generatedPhases, profileGeneratedCount, 0);
const lastEnrolledRelative =
  lastEnrolledPhase != null ? Math.max(0, lastEnrolledPhase - phaseStartOffset) : 0;
const displayPhaseProgress = Math.min(
  billedPhaseProgress,
  Number(profile.total_phases || 0) || billedPhaseProgress
);
const listNumerator = displayPhaseProgress + phaseStartOffset;
const listDenominator = Number(profile.total_phases || 0) + phaseStartOffset;

console.log({
  paid_phases_sql: paidPhases,
  generated_phases_sql: generatedPhases,
  profile_generated_count: profileGeneratedCount,
  last_enrolled_class_phase: lastEnrolledPhase,
  billing_phase_progress: billedPhaseProgress,
  display_phase_progress: displayPhaseProgress,
  list_ui_shows: `${listNumerator} / ${listDenominator} (Installment Invoice Logs — Phase Progress column)`,
});
console.log(
  `getCurrentInstallmentPhaseNumber (next bill absolute phase): ${getCurrentInstallmentPhaseNumber(profile)}`
);

section('C — Student History phases API (simulated)');
const downpaymentInvoiceId =
  profile.downpayment_invoice_id != null ? Number(profile.downpayment_invoice_id) : null;

const profileInvoices = invoices.filter((i) => Number(i.installmentinvoiceprofiles_id) === PROFILE_ID);
const chainMap = new Map();
for (const inv of profileInvoices) {
  const chainRoot = Number(inv.chain_root_id);
  if (!chainMap.has(chainRoot)) {
    chainMap.set(chainRoot, {
      chain_root_id: chainRoot,
      representative: inv,
      paid_amount: 0,
      latest_payment_date: null,
      invoices: [],
    });
  }
  const chain = chainMap.get(chainRoot);
  chain.invoices.push(inv);
  chain.paid_amount += Number(inv.paid_total || 0);
}

let downpaymentChain = null;
const phaseChains = [];
for (const chain of chainMap.values()) {
  if (downpaymentInvoiceId && chain.chain_root_id === downpaymentInvoiceId) {
    downpaymentChain = chain;
  } else if (!isCancelledInvoiceChain(chain)) {
    phaseChains.push(chain);
  }
}

const droppedAbsolutePhases = await loadDroppedAbsolutePhasesForProfile(pool, STUDENT_ID, CLASS_ID);
const chainByLocalPhase = mapPhaseChainsToLocalSlots(phaseChains, profile);

const hasLaterAbsoluteBilling = (absolutePhase) => {
  for (const local of chainByLocalPhase.keys()) {
    if (phaseStart + Number(local) - 1 > absolutePhase) return true;
  }
  return false;
};
const hasLaterAbsoluteEnrollment = (absolutePhase) => {
  for (const abs of activeEnrollmentPhases) {
    if (abs > absolutePhase) return true;
  }
  return false;
};

const graceDays = await resolveInstallmentGraceDays(pool, profile.branch_id);
const todayYmd = todayYmdManila();
const computeStatus = (invoiceStatus, dueDate, issueDate) =>
  computeInstallmentPhaseDisplayStatus({
    invoiceStatus,
    dueDateYmd: dueDate,
    issueDateYmd: issueDate,
    graceDays,
    todayYmd,
  });

const totalPhases = Number(profile.total_phases || 0);
const phases = [];
for (let localPhase = 1; localPhase <= totalPhases; localPhase += 1) {
  const chain = chainByLocalPhase.get(localPhase);
  if (!chain) {
    const absoluteGap = phaseStart + localPhase - 1;
    const isSkippedGap = droppedAbsolutePhases.has(absoluteGap);
    const isLateStartGap =
      !isSkippedGap &&
      !activeEnrollmentPhases.has(absoluteGap) &&
      (hasLaterAbsoluteBilling(absoluteGap) || hasLaterAbsoluteEnrollment(absoluteGap));
    phases.push({
      phase_number: localPhase,
      invoice_id: null,
      status: isLateStartGap ? null : 'Not Generated',
      is_generated: false,
      amount: isLateStartGap ? null : Number(profile.amount),
      paid_amount: isLateStartGap ? null : 0,
      billing_kind: isSkippedGap ? 'skipped_gap' : isLateStartGap ? 'late_start_gap' : null,
    });
    continue;
  }
  const rep = chain.representative;
  const amount = rep.amount != null ? Number(rep.amount) : null;
  const paidAmount = Number(chain.paid_amount || 0);
  const profilePhaseAmount = Number(profile.amount || 0);
  const expectedAmount = amount != null ? amount : profilePhaseAmount;
  let displayStatus = computeStatus(rep.status, rep.due_date, rep.issue_date);
  if (Math.max(0, expectedAmount - paidAmount) <= 0.009) displayStatus = 'Paid';
  else if (paidAmount > 0.009 && expectedAmount <= 0.009) displayStatus = 'Paid';
  phases.push({
    phase_number: localPhase,
    invoice_id: Number(rep.invoice_id),
    status: displayStatus,
    is_generated: true,
    is_auto_generated: isAutoGeneratedInstallmentInvoice(rep),
    amount,
    paid_amount: paidAmount,
    billing_kind: isAdvancePaymentInvoice(rep) ? 'advance' : null,
  });
}

let normalizedPhases = annotateInstallmentPhasePlanSlots(
  normalizeAdjacentPhaseDisplayDates(phases, computeStatus)
);
const enrollmentByPhase = await loadEnrollmentStatusByAbsolutePhase(query, STUDENT_ID, CLASS_ID);
normalizedPhases = attachEnrollmentToInstallmentPhaseRows(normalizedPhases, {
  phaseStart,
  enrollmentByAbsolutePhase: enrollmentByPhase,
});

console.log('\nPhase rows (plan slot → invoice):');
for (const p of normalizedPhases.slice(0, 6)) {
  console.log(
    `  Slot ${p.phase_number} (class ph. ${p.absolute_phase_number}): ` +
      `billing=${p.billing_kind || '—'} gen=${p.is_generated} status=${p.status || '—'} ` +
      `inv=${p.invoice_id || '—'} enrollment=${p.program_enrollment_status || '—'} ` +
      `addressed=${p.plan_slot_addressed}`
  );
}

const generatedCount = normalizedPhases.filter((p) => p.is_generated).length;
const paidCount = normalizedPhases.filter((p) => {
  const st = String(p.status || '').toLowerCase();
  return st === 'paid' || st === 'paid all';
}).length;
const addressedCount = normalizedPhases.filter((p) => p.plan_slot_addressed).length;
const lateStartGaps = normalizedPhases.filter((p) => p.billing_kind === 'late_start_gap').length;

const historyPaidDisplay = paidCount + phaseStartOffset;
const historyGeneratedDisplay = generatedCount + phaseStartOffset;
const historyDenominator = totalPhases + phaseStartOffset;

console.log('\nStudent History UI (InstallmentPlanDetails):');
console.log({
  phases_complete: `${addressedCount} / ${totalPhases}`,
  paid: `${historyPaidDisplay} / ${historyDenominator}`,
  generated: `${historyGeneratedDisplay} / ${historyDenominator}`,
  late_start_gap_slots: lateStartGaps,
});

section('D — Expected when enrollment starts on class phase 2');
const expected = {
  first_enrolled_class_phase: 2,
  plan_slot_1: 'late_start_gap — all dashes, no Pay Now',
  plan_slots_with_invoices: '2 (INV-311 paid), 3 (INV-571 paid), 4 (INV-1012 unpaid)',
  paid_installment_invoices: 2,
  generated_installment_invoices: 3,
  profile_generated_count: 3,
  paid_phases_sql: 2,
  generated_phases_sql: 3,
  student_history_complete: '2 / 9 (paid slots 2–3 only; phase 1 hidden)',
  student_history_paid: '3 / 10 (downpayment + 2 installment phases)',
  student_history_generated: '3 / 10',
  modal_phase_1: 'hidden (late_start_gap)',
};
console.log(expected);

section('E — Verdict');
const issues = [];

if (firstEnrolledPhase !== 2) {
  issues.push(`First active enrollment is class phase ${firstEnrolledPhase}, expected 2`);
}
for (const [slot, invId, tp] of [
  [2, 311, 2],
  [3, 571, 3],
  [4, 1012, 4],
]) {
  const chain = chainByLocalPhase.get(slot);
  const inv = chain?.representative?.invoice_id;
  const target = parseTargetPhase(chain?.representative?.remarks);
  if (Number(inv) !== invId) issues.push(`Plan slot ${slot}: expected INV-${invId}, got ${inv || 'empty'}`);
  if (target !== tp) issues.push(`Plan slot ${slot}: expected TARGET_PHASE:${tp}, got ${target ?? 'none'}`);
}
const slot1 = normalizedPhases.find((p) => p.phase_number === 1);
if (slot1?.billing_kind !== 'late_start_gap') {
  issues.push(`Plan slot 1 should be late_start_gap, got ${slot1?.billing_kind || 'none'}`);
}
if (profileGeneratedCount !== 3) {
  issues.push(`profile.generated_count is ${profileGeneratedCount}, expected 3`);
}
if (paidPhases !== 2) issues.push(`paid_phases SQL is ${paidPhases}, expected 2`);
if (generatedPhases !== 3) issues.push(`generated_phases SQL is ${generatedPhases}, expected 3`);
if (paidCount !== 2) issues.push(`Student History paid count is ${paidCount}, expected 2`);
if (generatedCount !== 3) issues.push(`Student History generated count is ${generatedCount}, expected 3`);

if (issues.length === 0) {
  console.log('OK — Progress metrics align with late-start enrollment on class phase 2.');
  console.log(
    `Installment Logs: ${listNumerator}/${listDenominator} | ` +
      `Student History: ${addressedCount}/${totalPhases} complete, ` +
      `${historyPaidDisplay}/${historyDenominator} paid, ` +
      `${historyGeneratedDisplay}/${historyDenominator} generated`
  );
} else {
  console.log('ISSUES FOUND:');
  issues.forEach((msg, i) => console.log(`  ${i + 1}. ${msg}`));
}

await pool.end();
process.exit(issues.length > 0 ? 1 : 0);
